const ReviewsData = [
    {
      facultyName: "Tanjim Abubokor",
      totalReviews: 12,
      ratings: 4.5,
      poor: 3,
      fair: 6,
      good: 2,
      veryGood: 3,
      excellent: 4,
    },
    {
      facultyName: "Rahim Uddin",
      totalReviews: 20,
      ratings: 4.2,
      poor: 2,
      fair: 5,
      good: 4,
      veryGood: 5,
      excellent: 4,
    },
    {
      facultyName: "Karim Hossain",
      totalReviews: 18,
      ratings: 3.8,
      poor: 4,
      fair: 6,
      good: 5,
      veryGood: 2,
      excellent: 1,
    },
    {
      facultyName: "Ayesha Siddiqua",
      totalReviews: 25,
      ratings: 4.7,
      poor: 1,
      fair: 2,
      good: 4,
      veryGood: 8,
      excellent: 10,
    },
    {
      facultyName: "Md. Shahidul Islam",
      totalReviews: 15,
      ratings: 4.1,
      poor: 2,
      fair: 4,
      good: 5,
      veryGood: 3,
      excellent: 1,
    },
    {
      facultyName: "Fatima Akter",
      totalReviews: 30,
      ratings: 4.9,
      poor: 0,
      fair: 1,
      good: 2,
      veryGood: 10,
      excellent: 17,
    },
    {
      facultyName: "Hasan Mahmud",
      totalReviews: 22,
      ratings: 4.0,
      poor: 3,
      fair: 4,
      good: 6,
      veryGood: 5,
      excellent: 4,
    },
    {
      facultyName: "Nusrat Jahan",
      totalReviews: 28,
      ratings: 4.6,
      poor: 1,
      fair: 3,
      good: 5,
      veryGood: 7,
      excellent: 12,
    },
    {
      facultyName: "Arif Rahman",
      totalReviews: 17,
      ratings: 3.9,
      poor: 5,
      fair: 4,
      good: 3,
      veryGood: 3,
      excellent: 2,
    },
    {
      facultyName: "Sadia Ahmed",
      totalReviews: 19,
      ratings: 4.3,
      poor: 2,
      fair: 3,
      good: 5,
      veryGood: 5,
      excellent: 4,
    },
    {
      facultyName: "Imran Hossain",
      totalReviews: 21,
      ratings: 4.4,
      poor: 2,
      fair: 5,
      good: 4,
      veryGood: 6,
      excellent: 4,
    },
    {
      facultyName: "Samira Akter",
      totalReviews: 26,
      ratings: 4.8,
      poor: 0,
      fair: 2,
      good: 3,
      veryGood: 9,
      excellent: 12,
    },
    {
      facultyName: "Farhan Kabir",
      totalReviews: 14,
      ratings: 3.7,
      poor: 4,
      fair: 6,
      good: 2,
      veryGood: 1,
      excellent: 1,
    },
    {
      facultyName: "Maliha Sultana",
      totalReviews: 29,
      ratings: 4.9,
      poor: 0,
      fair: 1,
      good: 3,
      veryGood: 10,
      excellent: 15,
    },
    {
      facultyName: "Nayeem Rahman",
      totalReviews: 23,
      ratings: 4.2,
      poor: 3,
      fair: 4,
      good: 5,
      veryGood: 6,
      excellent: 5,
    },
    {
      facultyName: "Tahmina Islam",
      totalReviews: 16,
      ratings: 4.0,
      poor: 2,
      fair: 4,
      good: 4,
      veryGood: 3,
      excellent: 3,
    },
    {
      facultyName: "Zahid Hasan",
      totalReviews: 27,
      ratings: 4.5,
      poor: 1,
      fair: 3,
      good: 4,
      veryGood: 9,
      excellent: 10,
    },
    {
      facultyName: "Munira Begum",
      totalReviews: 24,
      ratings: 4.6,
      poor: 2,
      fair: 3,
      good: 4,
      veryGood: 8,
      excellent: 7,
    },
    {
      facultyName: "Rafiul Islam",
      totalReviews: 20,
      ratings: 4.3,
      poor: 2,
      fair: 5,
      good: 4,
      veryGood: 5,
      excellent: 4,
    },
    {
      facultyName: "Sabrina Jahan",
      totalReviews: 31,
      ratings: 4.8,
      poor: 0,
      fair: 2,
      good: 3,
      veryGood: 10,
      excellent: 16,
    },
  ];
  
  export default ReviewsData;
  